openshift_installer_version: 4.2.0
openshift_installer_url_prefix: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_client_version }}'

openshift_installer:
  version: '{{ openshift_installer_version }}'
  archive_url: '{{ openshift_installer_url_prefix }}/openshift-install-linux-{{ openshift_client_version }}.tar.gz'
  sha256sum_url:  '{{ openshift_installer_url_prefix }}/sha256sum.txt'
