- name: Check if {{ name }} has already been downloaded
  stat:
    path: '{{ dest }}'
    get_checksum: True
    checksum_algorithm: sha256
  register: file

- name: Download {{ name }} from {{ url }}
  get_url:
    url: '{{ url }}'
    dest: '{{ dest }}'
  when: not file.stat.exists

- name: Compute the checksum of {{ dest }}
  stat:
    path: '{{ dest }}'
    get_checksum: True
    checksum_algorithm: sha256
  register: file

- name: Fail if the checksum is incorrect
  fail:
    msg: Downloaded file {{ file.stat.path }}. The file is corrupted.
  when: 'checksum != "" and file.stat.checksum != checksum'
