- name: Install haproxy
  yum:
    name: haproxy
    state: present
  become: True

- name: Allow HAProxy to listen on ports
  seport:
    ports: 6443, 22623
    proto: tcp
    setype: http_port_t
    state: present
  become: yes

- name: Check the status of firewalld
  command: firewall-cmd --state
  changed_when: False
  failed_when: False
  register: firewalld
  become: True

- name: Enable ports on firewall
  firewalld:
    port: '{{ item }}/tcp'
    permanent: True
    immediate: True
    state: enabled
  when: firewalld.rc == 0
  with_items:
    - 6443
    - 22623
    - 443
    - 80
  become: True

- name: Start haproxy
  service:
    name: haproxy
    enabled: True
    state: started
  become: True

- name: Add OpenShift nodes to the load balancer
  blockinfile:
    block: '{{ lookup("template", "haproxy.cfg") }}'
    dest: /etc/haproxy/haproxy.cfg
    backup: True
  notify: Restart haproxy
  become: True
