openshift_install_config:
  name: mycluster
  base_domain: example.com
  cluster_domain: mycluster.example.com
  master_replicas: 1
  worker_replicas: 0
  ssh_key: ''
  # This is a JSON formatted pull secret that you can obtain at
  # https://cloud.redhat.com when installing a new OpenShift cluster. There is a
  # button "Download pull secret" that downloads this pull secret for you.
  # The secret contains keys for downloading container images from several Red Hat
  # repositories like quay.io, registry.connect.redhat.com, registry.redhat.io and
  # also keys for authenticating against the cloud.openshift.com itself.
  pull_secret: ''
