- name: Ensure unzip is installed
  yum:
    name: unzip
    state: present
  become: True

- name: Download aws client archive file
  get_url:
    url: '{{ aws_client.archive_url }}'
    dest: '{{ builder.install_bin_dir }}/{{ aws_client.archive_url | basename }}'

- name: Extract aws client installer
  unarchive:
    src: '{{ builder.install_bin_dir }}/{{ aws_client.archive_url | basename }}'
    dest: '{{ builder.install_bin_dir }}'
    creates: '{{ builder.install_bin_dir }}/awscli-bundle/install'

- name: Install aws client
  command: |
    {{ builder.install_bin_dir }}/awscli-bundle/install \
      --install-dir  {{ builder.install_bin_dir }}/awscli-install \
      --bin-location {{ builder.install_bin_dir }}/aws
  args:
    creates: '{{ builder.install_bin_dir }}/aws'
