- name: Install prerequisites
  import_role:
    name: openshift_generic
    tasks_from: prereqs.yml

- name: Install pyghmi required by Ansible
  yum:
    name: '{{ rpm_name["python-pyghmi"] }}'
    state: present
  become: True
