- name: Set CoreOS download url
  set_fact:
    installer_initramfs_url: 'coreos.{{ openshift_install_config.version }}.installer_initramfs_url'
    installer_kernel_url:    'coreos.{{ openshift_install_config.version }}.installer_kernel_url'
    metal_bios_url:          'coreos.{{ openshift_install_config.version }}.metal_bios_url'
    sha256sum_url:           'coreos.{{ openshift_install_config.version }}.sha256sum_url'

- name: Download CoreOS binaries
  get_url:
    url: '{{ item }}'
    dest: '{{ builder.web_cluster_dir }}/{{ item | basename }}'
    checksum: 'sha256:{{ sha256sum_url }}'
  with_items:
    - '{{ installer_initramfs_url }}'
    - '{{ installer_kernel_url }}'
    - '{{ metal_bios_url }}'
