- name: Read the bootstrap ignition data
  slurp:
    src: '{{ builder.install_cluster_dir }}/bootstrap.ign'
  register: bootstrap_ign

- name: Parse the x509 ca certificate
  set_fact:
    cert_data: '{{
      ((bootstrap_ign.content | b64decode | from_json).storage.files |
      selectattr("path", "match", "/opt/openshift/tls/root-ca.crt") | first )
      .contents.source.split(",").1 | b64decode }}'

- name: Create a temporary cert file
  tempfile:
    state: file
    suffix: -root-ca-cert
  changed_when: False
  register: cert_file

- debug:
    msg: Created temporary cert file {{ cert_file.path }}

- name: Save the cert data into file {{ cert_file.path }}
  copy:
    content: '{{ cert_data }}'
    dest: '{{ cert_file.path }}'
  changed_when: False

- name: Parse the cert data
  openssl_certificate_info:
    path: '{{ cert_file.path }}'
    valid_at:
      day_before_now: '-1d'
  register: result

- name: Delete a temporary cert file
  file:
    path: '{{ cert_file.path }}'
    state: absent
  changed_when: False

- name: Display certificate if too old
  debug:
    var: result
  when: result.valid_at.day_before_now

- fail:
    msg: >
      OpenShift root CA certificate is more than 24 hours old. Remove all the generated ignition files
      from the {{ builder.install_cluster_dir }}/ directory. Also remove the hidden state file
      {{ builder.install_cluster_dir }}/.openshift_install_state.json and then re-run the Ansible
      scripts.
  when: result.valid_at.day_before_now
